development:
  adapter: mysql2
  database: softgroup
  username: root
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: softgroup_test
  username: root
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: softgroup
  username: root
  host: localhost
  pool: 5
  timeout: 5000
