source 'https://rubygems.org'

gem 'best_in_place', '~> 3.0.1'
gem 'ckeditor', '4.1.3'
gem 'paperclip'
gem 'faraday'
gem 'mysql2', '0.3.21'
gem 'rails', '3.2.22.5'
gem 'slim-rails'
gem 'sqlite3'
gem 'social-share-button'
gem 'test-unit', '~> 3.0'
gem 'yaml_db'
gem 'truncate_html'
gem 'will_paginate', '~> 3.1.0'

group :assets do
  gem 'bootstrap-datepicker-rails'
  gem 'bootstrap-sass', '3.1.1.0'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'font-awesome-rails'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'uglifier', '>= 1.0.3'
end

group :test, :development do
  gem 'rspec-rails'
end

gem 'bcrypt-ruby', require: 'bcrypt'
gem 'jquery-rails'
gem 'pry-rails', group: :development
