source 'https://rubygems.org'

gem 'rails', '3.2.22.5'
gem 'slim-rails'
gem 'sqlite3'
gem 'test-unit', '~> 3.0'

group :assets do
  gem 'bootstrap-sass', '3.1.1.0'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'uglifier', '>= 1.0.3'
end

gem 'bcrypt-ruby', require: 'bcrypt'
gem 'jquery-rails'
gem 'pry-rails', group: :development
