source 'https://rubygems.org'

gem 'rails', '3.2.22.5'
gem 'sqlite3'
gem 'test-unit', '~> 3.0'

group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'pry-rails', :group => :development
